# Generated by Django 4.2 on 2023-04-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phones',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterField(
            model_name='phones',
            name='video',
            field=models.URLField(blank=True, verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, null=True, verbose_name='Комментарий')),
                ('rate', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], null=True, verbose_name='Оценка')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('choice_phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='phone_app.phones')),
            ],
        ),
    ]
